package calculadora;

/**
 *
 * @author Edgar Montiel
 */
public class Interfaz extends javax.swing.JFrame {

    //Creación del objeto calc: 
    Calculadora calc = new Calculadora();

    String numero, numero2, signo;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setSize(400, 600); // Configuramos dimensiones
        this.setLocationRelativeTo(null); //Centamos la pantalla. 
        setTitle("Calculadora"); // Asignamos el titulo al Frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Entrada = new javax.swing.JTextField();
        num0 = new javax.swing.JButton();
        numero1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        numero6 = new javax.swing.JButton();
        numero7 = new javax.swing.JButton();
        numero8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        producto = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Entrada.setBackground(new java.awt.Color(102, 102, 102));
        Entrada.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaActionPerformed(evt);
            }
        });
        jPanel1.add(Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 310, 130));

        num0.setBackground(new java.awt.Color(102, 102, 102));
        num0.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        jPanel1.add(num0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 130, 50));

        numero1.setBackground(new java.awt.Color(102, 102, 102));
        numero1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        numero1.setText("1");
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });
        jPanel1.add(numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 56, 52));

        num2.setBackground(new java.awt.Color(102, 102, 102));
        num2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        jPanel1.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 56, 52));

        num3.setBackground(new java.awt.Color(102, 102, 102));
        num3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        jPanel1.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 56, 52));

        num4.setBackground(new java.awt.Color(102, 102, 102));
        num4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        jPanel1.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 56, 52));

        num5.setBackground(new java.awt.Color(102, 102, 102));
        num5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        jPanel1.add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 56, 52));

        numero6.setBackground(new java.awt.Color(102, 102, 102));
        numero6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        numero6.setText("6");
        numero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero6ActionPerformed(evt);
            }
        });
        jPanel1.add(numero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 56, 52));

        numero7.setBackground(new java.awt.Color(102, 102, 102));
        numero7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        numero7.setText("7");
        numero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero7ActionPerformed(evt);
            }
        });
        jPanel1.add(numero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 56, 52));

        numero8.setBackground(new java.awt.Color(102, 102, 102));
        numero8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        numero8.setText("8");
        numero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero8ActionPerformed(evt);
            }
        });
        jPanel1.add(numero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 56, 52));

        num9.setBackground(new java.awt.Color(102, 102, 102));
        num9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        jPanel1.add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 56, 52));

        mas.setBackground(new java.awt.Color(102, 102, 102));
        mas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mas.setText("+");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });
        jPanel1.add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 56, 52));

        menos.setBackground(new java.awt.Color(102, 102, 102));
        menos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        jPanel1.add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 56, 52));

        punto.setBackground(new java.awt.Color(102, 102, 102));
        punto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        punto.setText(".");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        jPanel1.add(punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 56, 52));

        dividir.setBackground(new java.awt.Color(102, 102, 102));
        dividir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dividir.setText("/");
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });
        jPanel1.add(dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 56, 52));

        producto.setBackground(new java.awt.Color(102, 102, 102));
        producto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        producto.setText("x");
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });
        jPanel1.add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 56, 52));

        igual.setBackground(new java.awt.Color(102, 102, 102));
        igual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        jPanel1.add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 60, 120));

        Limpiar.setBackground(new java.awt.Color(102, 102, 102));
        Limpiar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Limpiar.setText("C");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 56, 52));

        borrar.setBackground(new java.awt.Color(102, 102, 102));
        borrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        borrar.setText("DEL");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jPanel1.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 56, 52));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // Borrar el ultimo caracter del textfield

        String cadena; //Declaración de la variable cadena de tipo String
        cadena = Entrada.getText(); // Se le asigna a cadena el valor del textfield

        if (cadena.length() > 0) { //Condicionamos que haya elementos en patalla
            // Si hay elementos, entonces borramos un caracter de pantalla
            Entrada.setText(Entrada.getText().substring(0, Entrada.getText().length() - 1));

        }
    }//GEN-LAST:event_borrarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        //Limpieza total del textfield

        Entrada.setText(null); // Borra el contenido del textfield
        Entrada.requestFocus(); //Asignamos el foco al textfield

    }//GEN-LAST:event_LimpiarActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        // Boton de multiplicacion

        if (!Entrada.getText().equals("")) {  // Si pantalla no esta vacía: 
            numero = Entrada.getText(); // Declaramos la variable numero y le asignamos el valor en pantalla
            signo = "x"; //Asignamos el signo. 
            Entrada.setText(""); // Mostramos la pantalla vacia
        }
    }//GEN-LAST:event_productoActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        //Boton  de division

        if (!Entrada.getText().equals("")) {
            numero = Entrada.getText();
            signo = "/";
            Entrada.setText("");
        }
    }//GEN-LAST:event_dividirActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed

        String cadena_texto; // Definimos una variable de tipo String
        cadena_texto = Entrada.getText(); // Le asignamos a la variable lo que el textField contenga

        if (cadena_texto.length() <= 0) { // Comparamos que la cadena no esté vacía
            Entrada.setText("0."); // Si la cadena esta vacía, se inserta el valor establecido
        } else if (!calc.punto(Entrada.getText())) { // LLamado al método punto, si en patalla hay valores
            Entrada.setText(Entrada.getText() + ".");

        }
    }//GEN-LAST:event_puntoActionPerformed


    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // TODO add your handling code here:

        String resultado; //Declaramos una variable de tipo string que guardara el resultado
        numero2 = Entrada.getText(); // La variable numero ya tiene valor, por ende proseguimos a asignarle a la variable numero2 el valor en pantalla

        if (!numero.equals("")) { // Condicionamos que la pantalla no este vacía
            // En la variable resultado guardamos lo que nos retorne el metodo operaciones:
            resultado = calc.operaciones(numero, numero2, signo);  // Envíamos como parémetros los valores
            Entrada.setText(resultado); // Finalmente mostramos en pantalla lo retornado
        }
    }//GEN-LAST:event_igualActionPerformed

    

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        
    //Boton sumatoria: 
        if (!Entrada.getText().equals("")) {
            numero = Entrada.getText();
            signo = "+";  //Asignamos el signo de suma como String
            Entrada.setText("");
        }
    }//GEN-LAST:event_masActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
       
    //Boton resta:
        if (!Entrada.getText().equals("")) {
            numero = Entrada.getText();
            signo = "-";
            Entrada.setText("");
        }

    }//GEN-LAST:event_menosActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // boton de ingreso del 9:

        Entrada.setText(Entrada.getText()+ "9"); // Concatenamos lo que este en pantalla, más el valor establecido
    }//GEN-LAST:event_num9ActionPerformed

    private void numero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero8ActionPerformed
        //Boton de ingreso del 8:

        Entrada.setText(Entrada.getText() + "8");
    }//GEN-LAST:event_numero8ActionPerformed

    private void numero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero7ActionPerformed
        //Boton de ingreso para el numero 7:

        Entrada.setText(Entrada.getText() + "7");
    }//GEN-LAST:event_numero7ActionPerformed

    private void numero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero6ActionPerformed
        //Boton para el numero 6:

        Entrada.setText(Entrada.getText() + "6");
    }//GEN-LAST:event_numero6ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // Boton de ingreso del numero 5:

        Entrada.setText(Entrada.getText() + "5");
    }//GEN-LAST:event_num5ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        //Boton de ingreso del numero 4:

        Entrada.setText(Entrada.getText() + "4");
    }//GEN-LAST:event_num4ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        //Boton de ingreso del numero 3:

        Entrada.setText(Entrada.getText() + "3");
    }//GEN-LAST:event_num3ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        //Boton de ingreso del numero 2:

        Entrada.setText(Entrada.getText() + "2");
    }//GEN-LAST:event_num2ActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        //Boton de ingreso de numeros 1:

        Entrada.setText(Entrada.getText() + "1");
    }//GEN-LAST:event_numero1ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // Boton de ingreso del numero 0:

        Entrada.setText(Entrada.getText() + "0");
    }//GEN-LAST:event_num0ActionPerformed

    private void EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaActionPerformed

    }//GEN-LAST:event_EntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Entrada;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton borrar;
    private javax.swing.JButton dividir;
    private javax.swing.JButton igual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton num0;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num9;
    private javax.swing.JButton numero1;
    private javax.swing.JButton numero6;
    private javax.swing.JButton numero7;
    private javax.swing.JButton numero8;
    private javax.swing.JButton producto;
    private javax.swing.JButton punto;
    // End of variables declaration//GEN-END:variables
}
